##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [2.26.0] date: [Mon Aug 20 16:36:15 EEST 2018]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET := $(notdir $(shell pwd))


######################################
# building variables
######################################
# debug build?
#DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################


# firmware library path
PERIFLIB_PATH = 

# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources

C_SOURCES = src/main.c
C_SOURCES += cmsis/src/system_stm32f0xx.c

C_SOURCES += STM32F0xx_StdPeriph_Driver/src/stm32f0xx_adc.c
C_SOURCES += STM32F0xx_StdPeriph_Driver/src/stm32f0xx_gpio.c
C_SOURCES += STM32F0xx_StdPeriph_Driver/src/stm32f0xx_dma.c
C_SOURCES += STM32F0xx_StdPeriph_Driver/src/stm32f0xx_usart.c
C_SOURCES += STM32F0xx_StdPeriph_Driver/src/stm32f0xx_rcc.c
C_SOURCES += STM32F0xx_StdPeriph_Driver/src/stm32f0xx_misc.c
C_SOURCES += STM32F0xx_StdPeriph_Driver/src/stm32f0xx_tim.c

# ASM sources
ASM_SOURCES = cmsis/src/startup_stm32f030x6.s



######################################
# firmware library
######################################
PERIFLIB_SOURCES = 


#######################################
# binaries
#######################################
BINPATH = /usr/bin
PREFIX = arm-none-eabi-
CC = $(BINPATH)/$(PREFIX)gcc
AS = $(BINPATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(BINPATH)/$(PREFIX)objcopy
AR = $(BINPATH)/$(PREFIX)ar
SZ = $(BINPATH)/$(PREFIX)size
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m0

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
#C_DEFS = -DSTM32F030x6
#C_DEFS += -DSTM32F030X6
#C_DEFS += -DSTM32F030

#-DUSE_HAL_DRIVER \

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES = -Iinc
C_INCLUDES += -Icmsis/inc
C_INCLUDES += -ISTM32F0xx_StdPeriph_Driver/inc


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections



# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = cmsis/STM32F030F4Px_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys
LIBDIR =
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections


# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf  $(TARGET).bin
#$(BUILD_DIR)/$(TARGET).hex

#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))



$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	@echo c cource: $(@F)
	@$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@
	@$(SZ) $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	@echo asm source: $(@F)
	@$(AS) -c $(CFLAGS) $< -o $@
	@$(SZ) $@
	
$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	@echo link: $(@F)
	@$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	@$(SZ) $@

#$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
#	$(HEX) $< $@
	
%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR .dep $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(shell mkdir .dep 2>/dev/null) $(wildcard .dep/*)

# *** EOF ***
